import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Neon Pulse ── Premium com marquee, counter, split-content */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "neon-pulse",
  meta: {
    title: "Neon Pulse",
    description:
      "Template futurista dark com magenta neon. Marquee, contadores animados e split-content.",
  },
  theme: {
    colors: {
      gold: "#E040FB",
      goldLight: "#EA80FC",
      goldDark: "#D500F9",
      background: "#07040A",
      foreground: "#F0E6F6",
      beige: "#120A18",
      nude: "#1C0F25",
      cream: "#0A0610",
    },
    fonts: {
      heading: "Orbitron",
      body: "Exo 2",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "// proposal.init()",
        titleLine1: "Automacao &",
        titleHighlight: "Inteligencia Artificial",
        subtitle:
          "Implementamos IA e automacoes que eliminam trabalho manual, reduzem custos e escalam sua operacao 24/7.",
        clientName: "Nome da Empresa",
        ctaPrimary: { label: "Ver Solucao", scrollTo: "counter-1" },
        ctaSecondary: { label: "Agendar Demo", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["ChatGPT", "Automacao", "Machine Learning", "APIs", "Workflows", "Integracao", "Data Pipeline", "AI Agents"],
        speed: "fast",
        direction: "left",
        variant: "solid",
        separator: "slash",
        size: "sm",
        repeat: 3,
        pauseOnHover: false,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Impacto",
        title: "Resultados Comprovados",
        subtitle: "Numeros reais de empresas que automatizamos.",
        items: [
          { value: 85, prefix: "", suffix: "%", label: "Reducao de Trabalho Manual" },
          { value: 3, prefix: "", suffix: "x", label: "Mais Produtividade" },
          { value: 40, prefix: "R$", suffix: "k", label: "Economia Mensal Media" },
          { value: 24, prefix: "", suffix: "/7", label: "Operacao Automatica" },
        ],
        columns: 4,
        duration: 1800,
        style: "bordered",
      },
    },
    {
      id: "split-1",
      type: "split-content",
      visible: true,
      data: {
        layout: "image-left",
        image: "",
        imageAlt: "Dashboard de automacao",
        imageFit: "cover",
        sectionLabel: "Como Funciona",
        title: "IA Trabalhando Por Voce",
        body: "Nossos agentes de IA aprendem o fluxo da sua empresa e executam tarefas repetitivas automaticamente. Atendimento, triagem, relatorios, follow-ups — tudo no piloto automatico.",
        items: [
          "Chatbots inteligentes com GPT-4",
          "Automacao de emails e follow-ups",
          "Integracao com seu CRM e ferramentas",
          "Dashboard de monitoramento em tempo real",
        ],
        buttonLabel: "Agendar Demo",
        buttonUrl: "https://wa.me/5500000000000",
        verticalAlign: "center",
        imageRounded: true,
      },
    },
    {
      id: "estrategia-1",
      type: "estrategia",
      visible: true,
      data: {
        sectionLabel: "Stack",
        title: "Nossa Abordagem",
        subtitle: "Combinamos as melhores ferramentas de IA com engenharia de software para criar solucoes sob medida.",
        cards: [
          {
            icon: "Bot",
            title: "AI Agents",
            description: "Agentes inteligentes que executam tarefas complexas de forma autonoma.",
            items: ["Atendimento ao cliente automatizado", "Triagem e classificacao de leads", "Geracao de relatorios automaticos", "Analise de sentimento em tempo real"],
          },
          {
            icon: "Workflow",
            title: "Automacao de Processos",
            description: "Workflows automatizados que conectam todas as suas ferramentas.",
            items: ["Integracao de 100+ ferramentas", "Automacao de onboarding de clientes", "Notificacoes e alertas inteligentes", "Sincronizacao de dados entre sistemas"],
          },
          {
            icon: "BarChart3",
            title: "Analytics & BI",
            description: "Dashboards que transformam dados brutos em insights acionaveis.",
            items: ["Dashboard customizado para seu negocio", "Previsao de vendas com ML", "Alertas de anomalias automaticos", "Relatorios exportaveis para stakeholders"],
          },
        ],
      },
    },
    {
      id: "pricing-1",
      type: "pricing-table",
      visible: true,
      data: {
        sectionLabel: "Planos",
        title: "Escolha Seu Nivel de Automacao",
        subtitle: "Do basico ao enterprise, temos a solucao ideal para sua operacao.",
        plans: [
          {
            name: "Starter",
            badge: "",
            price: "R$ 2.900",
            currency: "R$",
            period: "/mes",
            features: [
              "Ate 3 automacoes ativas",
              "1 chatbot com IA",
              "Integracoes basicas (5 tools)",
              "Dashboard simples",
              "Suporte por email",
            ],
            ctaLabel: "Comecar", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
          {
            name: "Business",
            badge: "Mais Popular",
            price: "R$ 5.900",
            currency: "R$",
            period: "/mes",
            features: [
              "Automacoes ilimitadas",
              "3 chatbots com IA",
              "Integracoes avancadas (20+ tools)",
              "Dashboard completo + BI",
              "Suporte prioritario",
              "Treinamento da equipe",
            ],
            ctaLabel: "Escolher Business", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: true,
          },
          {
            name: "Enterprise",
            badge: "",
            price: "Sob consulta",
            currency: "",
            period: "",
            features: [
              "Tudo do Business +",
              "AI Agents customizados",
              "Integracao com sistemas legados",
              "SLA garantido 99.9%",
              "Gerente de conta dedicado",
              "Auditoria de seguranca",
            ],
            ctaLabel: "Falar com Especialista", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
        ],
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Futuro",
        title: "Sua Empresa no Piloto Automatico",
        subtitle: "Imagine sua equipe focada no que realmente importa enquanto a IA cuida do resto.",
        items: [
          { icon: "Zap", label: "Operacao rodando 24/7 sem intervencao humana" },
          { icon: "DollarSign", label: "Custos operacionais reduzidos drasticamente" },
          { icon: "TrendingUp", label: "Escala sem necessidade de contratar mais" },
          { icon: "Brain", label: "Decisoes inteligentes baseadas em dados reais" },
        ],
        quote: "A pergunta nao e se voce vai automatizar. E se vai fazer isso antes ou depois da concorrencia.",
        quoteHighlight: "antes ou depois da concorrencia",
        footerClientName: "Nome da Empresa",
        footerNote: "Proposta valida por 7 dias. Implementacao em ate 30 dias.",
      },
    },
  ],
};
