import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Forest Deep ── Premium com marquee, counter, timeline para academia */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "forest-deep",
  meta: {
    title: "Forest Deep",
    description:
      "Template dark premium verde floresta para personal trainers, crossfit e consultorias fitness.",
  },
  theme: {
    colors: {
      gold: "#22C55E",
      goldLight: "#4ADE80",
      goldDark: "#16A34A",
      background: "#030A06",
      foreground: "#E8F5EC",
      beige: "#0A1A0F",
      nude: "#122818",
      cream: "#050F08",
    },
    fonts: {
      heading: "Bebas Neue",
      body: "Barlow",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Assessoria Fitness",
        titleLine1: "Transformacao",
        titleHighlight: "Fisica & Mental",
        subtitle:
          "Programa de treinamento personalizado com acompanhamento nutricional para resultados reais e duradouros.",
        clientName: "Nome do Aluno",
        ctaPrimary: { label: "Ver Programa", scrollTo: "counter-1" },
        ctaSecondary: { label: "Agendar Avaliacao", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Hipertrofia", "Emagrecimento", "Performance", "Funcional", "Forca", "Mobilidade", "Resistencia"],
        speed: "normal",
        direction: "left",
        variant: "solid",
        separator: "diamond",
        size: "lg",
        repeat: 3,
        pauseOnHover: true,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Resultados",
        title: "Transformacoes Reais",
        subtitle: "Numeros dos nossos alunos nos ultimos 12 meses.",
        items: [
          { value: 500, prefix: "+", suffix: "", label: "Alunos Transformados" },
          { value: 12, prefix: "", suffix: "kg", label: "Perda Media em 90 Dias" },
          { value: 98, prefix: "", suffix: "%", label: "Aderencia ao Programa" },
          { value: 8, prefix: "", suffix: " anos", label: "Experiencia" },
        ],
        columns: 4,
        duration: 2000,
        style: "card",
      },
    },
    {
      id: "split-1",
      type: "split-content",
      visible: true,
      data: {
        layout: "image-left",
        image: "",
        imageAlt: "Treino personalizado",
        imageFit: "cover",
        sectionLabel: "Metodologia",
        title: "Treino Inteligente",
        body: "Cada treino e projetado especificamente para seus objetivos, limitacoes e estilo de vida. Sem planilhas genericas — tudo e feito sob medida.",
        items: [
          "Periodizacao individualizada",
          "Videos demonstrativos de cada exercicio",
          "Ajustes semanais com base no progresso",
          "App exclusivo com treinos e historico",
        ],
        buttonLabel: "Quero Comecar",
        buttonUrl: "https://wa.me/5500000000000",
        verticalAlign: "center",
        imageRounded: true,
      },
    },
    {
      id: "timeline-1",
      type: "timeline",
      visible: true,
      data: {
        sectionLabel: "Jornada",
        title: "Sua Transformacao em 12 Semanas",
        subtitle: "Programa estruturado em fases para resultados progressivos e sustentaveis.",
        items: [
          { icon: "ClipboardCheck", title: "Avaliacao Completa", description: "Avaliacao fisica, postural, composicao corporal e historico. Definicao de metas reais.", period: "Semana 0" },
          { icon: "Flame", title: "Fase de Adaptacao", description: "Aprendizado de movimentos, construcao de base e ajuste de alimentacao.", period: "Semana 1-4" },
          { icon: "Zap", title: "Fase Intensiva", description: "Progressao de carga, aumento de volume e intensificacao dos protocolos nutricionais.", period: "Semana 5-8" },
          { icon: "Trophy", title: "Fase de Resultado", description: "Peak de performance, refinamento estetico e consolidacao de habitos.", period: "Semana 9-12" },
        ],
        layout: "alternating",
        connectorStyle: "solid",
      },
    },
    {
      id: "pricing-1",
      type: "pricing-table",
      visible: true,
      data: {
        sectionLabel: "Planos",
        title: "Escolha Seu Programa",
        subtitle: "Programas para todos os niveis e objetivos.",
        plans: [
          {
            name: "Treino Online",
            badge: "",
            price: "R$ 197",
            currency: "R$",
            period: "/mes",
            features: [
              "Treino personalizado mensal",
              "Videos demonstrativos",
              "Ajustes quinzenais",
              "Suporte por WhatsApp",
              "Acesso ao app",
            ],
            ctaLabel: "Assinar", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
          {
            name: "Assessoria Completa",
            badge: "Mais Popular",
            price: "R$ 397",
            currency: "R$",
            period: "/mes",
            features: [
              "Treino + nutricao personalizados",
              "Ajustes semanais",
              "Check-in semanal por video",
              "Suporte prioritario 24h",
              "Acesso ao app premium",
              "Avaliacao fisica mensal",
            ],
            ctaLabel: "Quero Esse", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: true,
          },
          {
            name: "VIP Presencial",
            badge: "",
            price: "R$ 890",
            currency: "R$",
            period: "/mes",
            features: [
              "Tudo da Assessoria Completa +",
              "3 treinos presenciais/semana",
              "Acompanhamento em tempo real",
              "Suplementacao inclusa",
              "Acesso 24h a academia",
            ],
            ctaLabel: "Agendar", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
        ],
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Visao",
        title: "Seu Corpo, Sua Conquista",
        subtitle: "Imagine olhar no espelho daqui 12 semanas e nao reconhecer a versao anterior de voce.",
        items: [
          { icon: "Flame", label: "Corpo forte, definido e saudavel" },
          { icon: "Brain", label: "Mente mais clara e disposicao o dia todo" },
          { icon: "Heart", label: "Autoconfianca que transborda para todas as areas" },
          { icon: "Trophy", label: "Habitos saudaveis que duram para sempre" },
        ],
        quote: "O treino nao muda so seu corpo. Muda sua mente, sua confianca e a forma como voce enfrenta a vida.",
        quoteHighlight: "a forma como voce enfrenta a vida",
        footerClientName: "Nome do Aluno",
        footerNote: "Proposta valida por 7 dias. Vagas limitadas por mes.",
      },
    },
  ],
};
