import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Copper Warm ── Premium com marquee, counter, timeline p/ social media */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "copper-warm",
  meta: {
    title: "Copper Warm",
    description:
      "Template acolhedor com cobre quente para gestao de redes sociais, social media e conteudo.",
  },
  theme: {
    colors: {
      gold: "#D97706",
      goldLight: "#F59E0B",
      goldDark: "#B45309",
      background: "#FFFCF5",
      foreground: "#3D2800",
      beige: "#FFF3D6",
      nude: "#FFE8B8",
      cream: "#FFFAF0",
    },
    fonts: {
      heading: "Libre Baskerville",
      body: "Lato",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Social Media",
        titleLine1: "Gestao de",
        titleHighlight: "Redes Sociais",
        subtitle:
          "Conteudo estrategico que transforma seguidores em clientes. Gestao completa do Instagram, TikTok e LinkedIn da sua marca.",
        clientName: "Nome da Marca",
        ctaPrimary: { label: "Ver Plano", scrollTo: "counter-1" },
        ctaSecondary: { label: "Conversar no WhatsApp", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Instagram", "TikTok", "LinkedIn", "Reels", "Stories", "Carrosséis", "Conteudo", "Engajamento"],
        speed: "slow",
        direction: "left",
        variant: "outline",
        separator: "star",
        size: "md",
        repeat: 3,
        pauseOnHover: true,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Portfolio",
        title: "Nossos Resultados",
        subtitle: "",
        items: [
          { value: 80, prefix: "+", suffix: "", label: "Marcas Atendidas" },
          { value: 5, prefix: "", suffix: "M+", label: "Alcance Mensal" },
          { value: 340, prefix: "+", suffix: "%", label: "Aumento de Engajamento" },
          { value: 4, prefix: "", suffix: " anos", label: "No Mercado" },
        ],
        columns: 4,
        duration: 2000,
        style: "simple",
      },
    },
    {
      id: "diag-1",
      type: "diagnostico",
      visible: true,
      data: {
        sectionLabel: "Diagnostico",
        title: "Como Esta Sua Presenca Digital",
        subtitle: "Analisamos suas redes e identificamos o que precisa mudar para gerar resultados.",
        showImages: false,
        imagesLabel: "",
        images: [],
        cards: [
          { icon: "Image", title: "Conteudo Inconsistente", description: "Posts sem frequencia, sem identidade visual e sem estrategia. O algoritmo penaliza contas inativas.", severity: "alto" },
          { icon: "Users", title: "Seguidores que Nao Compram", description: "Numero de seguidores crescendo mas vendas estagnadas. Falta estrategia de conteudo voltada para conversao.", severity: "alto" },
          { icon: "MessageCircle", title: "Baixo Engajamento", description: "Poucas curtidas, comentarios e compartilhamentos. Sem engajamento, o alcance organico despenca.", severity: "medio" },
          { icon: "Star", title: "Marca com Personalidade", description: "Seu produto tem identidade propria e publico fiel. Com conteudo certo, o crescimento sera exponencial.", severity: "positivo" },
        ],
      },
    },
    {
      id: "timeline-1",
      type: "timeline",
      visible: true,
      data: {
        sectionLabel: "Processo",
        title: "Como Trabalhamos",
        subtitle: "Metodologia testada para transformar suas redes em maquinas de resultado.",
        items: [
          { icon: "Search", title: "Imersao na Marca", description: "Entendemos seu universo, publico, concorrentes e tom de voz. Nada generico.", period: "Semana 1" },
          { icon: "Calendar", title: "Planejamento Mensal", description: "Calendario editorial com 20+ posts estrategicos, stories diarios e reels semanais.", period: "Inicio de Cada Mes" },
          { icon: "Paintbrush", title: "Producao & Design", description: "Criacao de conteudo com design profissional, copy persuasiva e hashtags otimizadas.", period: "Continuo" },
          { icon: "BarChart3", title: "Analise & Otimizacao", description: "Relatorio mensal com metricas, insights e ajustes de estrategia baseados em dados.", period: "Fim de Cada Mes" },
        ],
        layout: "vertical",
        connectorStyle: "dashed",
      },
    },
    {
      id: "investimento-1",
      type: "investimento",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Plano de Gestao",
        subtitle: "Investimento mensal que se paga com os novos clientes gerados pelas redes.",
        badge: "Gestao Completa",
        priceOriginal: "R$ 2.500",
        priceCurrent: "R$ 1.790",
        priceCurrency: "R$",
        pricePeriod: "/mes",
        description: "Gestao completa das redes sociais com producao de conteudo, design e relatorios.",
        includedItems: [
          "20 posts mensais (feed + reels)",
          "Stories diarios (segunda a sexta)",
          "Design profissional para cada peca",
          "Copy estrategica e hashtags otimizadas",
          "Gerenciamento de DMs e comentarios",
          "Relatorio mensal com metricas",
          "Reuniao quinzenal de alinhamento",
        ],
        ctaLabel: "Comecar Gestao",
        ctaUrl: "https://wa.me/5500000000000",
        guarantee: "Sem fidelidade. Cancele quando quiser com 30 dias de aviso.",
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Resultado",
        title: "Sua Marca Dominando as Redes",
        subtitle: "Imagine ter redes sociais profissionais que atraem clientes todos os dias.",
        items: [
          { icon: "TrendingUp", label: "Crescimento organico consistente e qualificado" },
          { icon: "Heart", label: "Comunidade engajada que ama sua marca" },
          { icon: "DollarSign", label: "Vendas vindas diretamente das redes sociais" },
          { icon: "Clock", label: "Voce livre para focar no que faz de melhor" },
        ],
        quote: "Redes sociais nao sao sobre postar bonito. Sao sobre conectar com as pessoas certas no momento certo.",
        quoteHighlight: "conectar com as pessoas certas",
        footerClientName: "Nome da Marca",
        footerNote: "Proposta valida por 10 dias.",
      },
    },
  ],
};
