import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Electric Blue ── Premium com marquee, counter, pricing-table */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "electric-blue",
  meta: {
    title: "Electric Blue",
    description:
      "Template eletrico dark com azul vibrante para agencias de trafego pago e performance.",
  },
  theme: {
    colors: {
      gold: "#3B82F6",
      goldLight: "#60A5FA",
      goldDark: "#2563EB",
      background: "#030712",
      foreground: "#E8EDF5",
      beige: "#0B1223",
      nude: "#131D35",
      cream: "#060C1A",
    },
    fonts: {
      heading: "Manrope",
      body: "Inter",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Performance Marketing",
        titleLine1: "Trafego Pago",
        titleHighlight: "Que Gera Lucro",
        subtitle:
          "Gestao profissional de anuncios Meta, Google e TikTok. Foco obsessivo em ROAS e escala lucrativa.",
        clientName: "Nome da Empresa",
        ctaPrimary: { label: "Ver Resultados", scrollTo: "counter-1" },
        ctaSecondary: { label: "Agendar Call", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Meta Ads", "Google Ads", "TikTok Ads", "CRO", "ROAS", "Funil", "Criativos", "Performance"],
        speed: "fast",
        direction: "left",
        variant: "solid",
        separator: "dot",
        size: "sm",
        repeat: 4,
        pauseOnHover: false,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Track Record",
        title: "Resultados Reais",
        subtitle: "Metricas dos ultimos 12 meses dos nossos clientes.",
        items: [
          { value: 12, prefix: "R$", suffix: "M", label: "Gerenciados em Ads" },
          { value: 4, prefix: "", suffix: ".2x", label: "ROAS Medio" },
          { value: 300, prefix: "+", suffix: "%", label: "Crescimento de Vendas" },
          { value: 45, prefix: "+", suffix: "", label: "Clientes Ativos" },
        ],
        columns: 4,
        duration: 2000,
        style: "bordered",
      },
    },
    {
      id: "diag-1",
      type: "diagnostico",
      visible: true,
      data: {
        sectionLabel: "Audit",
        title: "Diagnostico da Sua Operacao",
        subtitle: "Analisamos suas campanhas atuais e identificamos oportunidades imediatas de melhoria.",
        showImages: false,
        imagesLabel: "",
        images: [],
        cards: [
          { icon: "AlertTriangle", title: "CPA Alto Demais", description: "O custo por aquisicao esta comendo sua margem. Sem otimizacao de publico e criativos, cada venda custa mais do que deveria.", severity: "alto" },
          { icon: "Filter", title: "Funil Mal Estruturado", description: "Campanhas sem funil logico. Trafego frio recebendo oferta direta sem aquecimento prévio gera desperdicio.", severity: "alto" },
          { icon: "RefreshCw", title: "Criativos Saturados", description: "Os mesmos anuncios rodando ha meses. Fadiga de criativos reduz CTR e aumenta CPM progressivamente.", severity: "medio" },
          { icon: "TrendingUp", title: "Mercado Aquecido", description: "Seu produto tem product-market fit comprovado. Com trafego otimizado, a escala e questao de tempo.", severity: "positivo" },
        ],
      },
    },
    {
      id: "estrategia-1",
      type: "estrategia",
      visible: true,
      data: {
        sectionLabel: "Playbook",
        title: "Estrategia de Performance",
        subtitle: "Metodologia testada em +R$12M em anuncios para escalar com lucro.",
        cards: [
          {
            icon: "Target",
            title: "Meta Ads",
            description: "Funil completo de aquisicao e retargeting para maximizar cada real investido.",
            items: ["Funil de 3 niveis: Topo, Meio e Fundo", "50+ criativos em rotacao por mes", "Publicos lookalike e retargeting avancado", "Teste de 15+ copys por campanha"],
          },
          {
            icon: "Search",
            title: "Google Ads",
            description: "Captura de demanda ativa com foco em intencao de compra.",
            items: ["Campanhas Search para termos de alta intencao", "Shopping Ads otimizado para e-commerce", "Performance Max com feeds otimizados", "Negative keywords e quality score"],
          },
          {
            icon: "BarChart3",
            title: "CRO & Otimizacao",
            description: "Otimizacao continua de landing pages e funil para maximizar conversao.",
            items: ["Testes A/B semanais de landing pages", "Heatmaps e gravacao de sessoes", "Otimizacao de checkout e formularios", "Acompanhamento de unit economics"],
          },
        ],
      },
    },
    {
      id: "pricing-1",
      type: "pricing-table",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Planos de Gestao",
        subtitle: "Fee fixo + percentual de midia. Alinhamento total de incentivos.",
        plans: [
          {
            name: "Growth",
            badge: "",
            price: "R$ 1.990",
            currency: "R$",
            period: "/mes",
            features: [
              "Ate R$ 10k em midia/mes",
              "1 plataforma (Meta ou Google)",
              "15 criativos/mes",
              "Relatorio semanal",
              "Reuniao quinzenal",
            ],
            ctaLabel: "Comecar", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
          {
            name: "Scale",
            badge: "Recomendado",
            price: "R$ 3.990",
            currency: "R$",
            period: "/mes",
            features: [
              "Ate R$ 50k em midia/mes",
              "Meta + Google Ads",
              "40 criativos/mes",
              "Dashboard em tempo real",
              "Reuniao semanal",
              "CRO e testes A/B",
            ],
            ctaLabel: "Escalar Agora", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: true,
          },
          {
            name: "Enterprise",
            badge: "",
            price: "R$ 7.990",
            currency: "R$",
            period: "/mes",
            features: [
              "Midia ilimitada",
              "Todas as plataformas",
              "Criativos ilimitados",
              "Equipe dedicada",
              "SLA de resposta 2h",
              "Gestao de influencers",
            ],
            ctaLabel: "Falar Conosco", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
        ],
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Resultado",
        title: "Vendas no Piloto Automatico",
        subtitle: "Imagine acordar todos os dias com vendas que entraram enquanto voce dormia.",
        items: [
          { icon: "DollarSign", label: "Faturamento escalando mes a mes com margem saudavel" },
          { icon: "Target", label: "Publico ideal encontrando sua oferta no momento certo" },
          { icon: "BarChart3", label: "Dashboard com todas as metricas em tempo real" },
          { icon: "TrendingUp", label: "ROAS consistente que permite reinvestir e crescer" },
        ],
        quote: "Trafego pago nao e gasto. E a forma mais rapida, mensuravel e escalavel de crescer um negocio.",
        quoteHighlight: "rapida, mensuravel e escalavel",
        footerClientName: "Nome da Empresa",
        footerNote: "Proposta valida por 7 dias. Onboarding em 48h apos aprovacao.",
      },
    },
  ],
};
