import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Gradient Aurora ── Premium com marquee, counter, timeline, split */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "gradient-aurora",
  meta: {
    title: "Gradient Aurora",
    description:
      "Template vibrante com verde-azul aurora. Timeline, contadores e split-content para web design.",
  },
  theme: {
    colors: {
      gold: "#06B6D4",
      goldLight: "#22D3EE",
      goldDark: "#0891B2",
      background: "#020617",
      foreground: "#E0F2FE",
      beige: "#0C1426",
      nude: "#132035",
      cream: "#06101E",
    },
    fonts: {
      heading: "Space Grotesk",
      body: "Outfit",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Web Design Premium",
        titleLine1: "Sites que",
        titleHighlight: "Convertem Visitantes",
        subtitle:
          "Design moderno, performance otimizada e foco em conversao. Criamos sites que sao maquinas de gerar leads e vendas.",
        clientName: "Nome da Empresa",
        ctaPrimary: { label: "Ver Processo", scrollTo: "timeline-1" },
        ctaSecondary: { label: "Solicitar Orcamento", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Next.js", "React", "Tailwind", "Figma", "Framer Motion", "Vercel", "SEO", "Performance"],
        speed: "normal",
        direction: "left",
        variant: "outline",
        separator: "dot",
        size: "md",
        repeat: 3,
        pauseOnHover: true,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Portfolio",
        title: "Nosso Historico",
        subtitle: "",
        items: [
          { value: 200, prefix: "+", suffix: "", label: "Sites Entregues" },
          { value: 95, prefix: "", suffix: "%", label: "Score PageSpeed" },
          { value: 3, prefix: "", suffix: "x", label: "Mais Conversao" },
          { value: 50, prefix: "+", suffix: "", label: "Clientes Ativos" },
        ],
        columns: 4,
        duration: 2000,
        style: "simple",
      },
    },
    {
      id: "split-1",
      type: "split-content",
      visible: true,
      data: {
        layout: "image-right",
        image: "",
        imageAlt: "Design responsivo",
        imageFit: "cover",
        sectionLabel: "Abordagem",
        title: "Design Orientado a Conversao",
        body: "Cada pixel tem um proposito. Combinamos estetica impecavel com psicologia de conversao para criar experiencias que encantam e vendem.",
        items: [
          "Design responsivo pixel-perfect",
          "Velocidade de carregamento < 2s",
          "SEO tecnico otimizado desde o inicio",
          "Testes A/B integrados ao lancamento",
        ],
        buttonLabel: "Ver Cases",
        buttonUrl: "#",
        verticalAlign: "center",
        imageRounded: true,
      },
    },
    {
      id: "timeline-1",
      type: "timeline",
      visible: true,
      data: {
        sectionLabel: "Etapas",
        title: "Do Briefing ao Go-Live",
        subtitle: "Processo transparente com entregas semanais e feedback continuo.",
        items: [
          { icon: "MessageSquare", title: "Briefing & UX Research", description: "Entendemos seu negocio, publico e objetivos. Analise de concorrencia e mapeamento de jornada do usuario.", period: "Semana 1" },
          { icon: "Paintbrush", title: "Wireframe & Design", description: "Prototipo navegavel no Figma com 2 rotas visuais. Voce participa de cada decisao de design.", period: "Semana 2-3" },
          { icon: "Code", title: "Desenvolvimento", description: "Frontend em Next.js com animacoes fluidas, backend otimizado e CMS para voce editar tudo sozinho.", period: "Semana 4-5" },
          { icon: "Rocket", title: "Testes & Lancamento", description: "QA completo, testes de performance e SEO. Deploy em Vercel com CDN global. Seu site voando.", period: "Semana 6" },
        ],
        layout: "vertical",
        connectorStyle: "dashed",
      },
    },
    {
      id: "diferenciais-1",
      type: "diferenciais",
      visible: true,
      data: {
        sectionLabel: "Stack",
        title: "Tecnologia de Ponta",
        subtitle: "Usamos o que ha de mais moderno em web development para entregar resultados superiores.",
        cards: [
          { icon: "Zap", title: "Ultra Rapido", description: "Sites com score 95+ no PageSpeed. Cada milissegundo importa para SEO e conversao." },
          { icon: "Smartphone", title: "Mobile First", description: "70% do trafego vem do mobile. Desenhamos primeiro para celular, depois adaptamos para desktop." },
          { icon: "Search", title: "SEO Nativo", description: "Estrutura semantica, meta tags, sitemap e schema markup configurados desde o dia 1." },
          { icon: "Shield", title: "Seguro & Escalavel", description: "HTTPS, headers de seguranca e arquitetura que suporta milhoes de acessos sem cair." },
        ],
      },
    },
    {
      id: "investimento-1",
      type: "investimento",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Investimento no Seu Site",
        subtitle: "Um site profissional e o vendedor que trabalha 24/7 sem pedir ferias.",
        badge: "Site Completo",
        priceOriginal: "R$ 12.000",
        priceCurrent: "R$ 8.900",
        priceCurrency: "R$",
        pricePeriod: "",
        description: "Projeto completo de design e desenvolvimento com CMS, SEO e performance otimizada.",
        includedItems: [
          "UX/UI Design customizado no Figma",
          "Desenvolvimento em Next.js + Tailwind",
          "CMS para editar conteudo sem dev",
          "SEO tecnico configurado",
          "Integracao com Google Analytics e Tag Manager",
          "Hospedagem inclusa por 1 ano",
          "3 meses de suporte",
        ],
        ctaLabel: "Quero Meu Site",
        ctaUrl: "https://wa.me/5500000000000",
        guarantee: "Pagamento em 3x. Codigo-fonte 100% seu.",
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Resultado",
        title: "Seu Site dos Sonhos",
        subtitle: "Imagine um site que voce tem orgulho de mostrar e que gera resultados reais.",
        items: [
          { icon: "Globe", label: "Site moderno que impressiona visitantes desde o primeiro segundo" },
          { icon: "TrendingUp", label: "Taxa de conversao acima da media do mercado" },
          { icon: "Search", label: "Aparecendo nas primeiras posicoes do Google" },
          { icon: "Smartphone", label: "Experiencia impecavel em qualquer dispositivo" },
        ],
        quote: "Seu site nao e um cartao de visita digital. E sua loja, seu vendedor e seu melhor argumento de vendas.",
        quoteHighlight: "seu melhor argumento de vendas",
        footerClientName: "Nome da Empresa",
        footerNote: "Proposta valida por 10 dias.",
      },
    },
  ],
};
