import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Luxe Noir ── Premium com marquee, counter, timeline */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "luxe-noir",
  meta: {
    title: "Luxe Noir",
    description:
      "Template ultra-premium dark com dourado. Marquee animado, contadores de impacto e timeline de projeto.",
  },
  theme: {
    colors: {
      gold: "#D4AF37",
      goldLight: "#E5C76B",
      goldDark: "#B8942E",
      background: "#050505",
      foreground: "#F5F0E8",
      beige: "#0D0D08",
      nude: "#1A1A10",
      cream: "#080805",
    },
    fonts: {
      heading: "Playfair Display",
      body: "Raleway",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Proposta Exclusiva",
        titleLine1: "Branding &",
        titleHighlight: "Identidade de Luxo",
        subtitle:
          "Criamos marcas que exalam sofisticacao. Do conceito a execucao, cada detalhe e pensado para posicionar seu negocio no topo.",
        clientName: "Nome do Cliente",
        ctaPrimary: { label: "Explorar Proposta", scrollTo: "counter-1" },
        ctaSecondary: { label: "Conversar Agora", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Branding", "Identidade Visual", "Naming", "Brand Strategy", "Packaging", "Luxury Design", "Art Direction"],
        speed: "normal",
        direction: "left",
        variant: "gradient",
        separator: "diamond",
        size: "lg",
        repeat: 3,
        pauseOnHover: true,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Track Record",
        title: "Numeros que Falam",
        subtitle: "Anos de experiencia criando marcas que dominam seus mercados.",
        items: [
          { value: 150, prefix: "+", suffix: "", label: "Marcas Criadas" },
          { value: 12, prefix: "", suffix: " anos", label: "De Experiencia" },
          { value: 98, prefix: "", suffix: "%", label: "Satisfacao" },
          { value: 35, prefix: "+", suffix: "M", label: "Em Faturamento Gerado" },
        ],
        columns: 4,
        duration: 2000,
        style: "card",
      },
    },
    {
      id: "diag-1",
      type: "diagnostico",
      visible: true,
      data: {
        sectionLabel: "Analise",
        title: "O Cenario da Sua Marca",
        subtitle: "Identificamos os pontos criticos que impedem sua marca de atingir o posicionamento premium.",
        showImages: false,
        imagesLabel: "",
        images: [],
        cards: [
          { icon: "Palette", title: "Identidade Desatualizada", description: "A marca atual nao reflete a qualidade do servico oferecido. Clientes premium julgam pela aparencia primeiro.", severity: "alto" },
          { icon: "Eye", title: "Falta de Coerencia Visual", description: "Materiais com estilos diferentes em cada canal. Sem brand guidelines, cada peca parece de uma empresa diferente.", severity: "alto" },
          { icon: "Target", title: "Posicionamento Generico", description: "A marca nao se diferencia dos concorrentes. Sem storytelling proprio, voce compete apenas por preco.", severity: "medio" },
          { icon: "Diamond", title: "Produto de Alto Valor", description: "Seu servico ja tem qualidade premium. Com uma marca a altura, a percepcao de valor sobe e o preco tambem.", severity: "positivo" },
        ],
      },
    },
    {
      id: "timeline-1",
      type: "timeline",
      visible: true,
      data: {
        sectionLabel: "Processo",
        title: "Jornada de Criacao",
        subtitle: "Um processo estruturado em 5 fases para criar uma marca que dura decadas.",
        items: [
          { icon: "Search", title: "Imersao & Discovery", description: "Mergulhamos no universo da sua marca, publico e concorrencia. Entrevistas, benchmarks e mapeamento de territorio.", period: "Semana 1-2" },
          { icon: "Lightbulb", title: "Estrategia de Marca", description: "Definicao de posicionamento, personalidade, tom de voz e arquitetura de marca com base nos insights da imersao.", period: "Semana 3" },
          { icon: "Paintbrush", title: "Design & Criacao", description: "Desenvolvimento de 3 rotas criativas para logo, paleta de cores, tipografia e elementos graficos.", period: "Semana 4-5" },
          { icon: "FileText", title: "Brand Book", description: "Manual completo com todas as regras de aplicacao, versoes, cores, tipografia e exemplos de uso.", period: "Semana 6" },
          { icon: "Rocket", title: "Lancamento & Rollout", description: "Implementacao da nova marca em todos os pontos de contato: digital, fisico e comunicacao.", period: "Semana 7-8" },
        ],
        layout: "alternating",
        connectorStyle: "solid",
      },
    },
    {
      id: "investimento-1",
      type: "investimento",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Investimento em Marca",
        subtitle: "Uma marca forte e o ativo mais valioso de qualquer empresa.",
        badge: "Branding Completo",
        priceOriginal: "R$ 18.000",
        priceCurrent: "R$ 12.900",
        priceCurrency: "R$",
        pricePeriod: "",
        description: "Projeto completo de branding com imersao, estrategia, design e brand book.",
        includedItems: [
          "Imersao e pesquisa de mercado",
          "Estrategia de posicionamento de marca",
          "3 rotas criativas para identidade visual",
          "Logo principal + versoes e submarks",
          "Paleta de cores e tipografia",
          "Brand book completo (50+ paginas)",
          "Papelaria e templates de redes sociais",
          "Arquivos em todos os formatos",
        ],
        ctaLabel: "Criar Minha Marca",
        ctaUrl: "https://wa.me/5500000000000",
        guarantee: "Pagamento em 3x. Revisoes ilimitadas na fase de design.",
      },
    },
    {
      id: "marquee-2",
      type: "marquee",
      visible: true,
      data: {
        items: ["Elegancia", "Sofisticacao", "Exclusividade", "Impacto", "Prestigio", "Excelencia"],
        speed: "slow",
        direction: "right",
        variant: "outline",
        separator: "star",
        size: "md",
        repeat: 4,
        pauseOnHover: false,
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Visao",
        title: "Uma Marca para a Eternidade",
        subtitle: "Imagine sua marca reconhecida instantaneamente, transmitindo luxo e confianca em cada ponto de contato.",
        items: [
          { icon: "Crown", label: "Marca percebida como referencia premium do setor" },
          { icon: "DollarSign", label: "Ticket medio maior pela percepcao de valor elevada" },
          { icon: "Heart", label: "Clientes fieis que se orgulham de associar-se a sua marca" },
          { icon: "Star", label: "Identidade coerente que transcende tendencias passageiras" },
        ],
        quote: "Marcas de luxo nao vendem produtos. Vendem pertencimento a um universo exclusivo.",
        quoteHighlight: "pertencimento a um universo exclusivo",
        footerClientName: "Nome do Cliente",
        footerNote: "Proposta valida por 10 dias. Atendemos no maximo 3 projetos simultaneos.",
      },
    },
  ],
};
