import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Arctic Silver ── Premium com marquee, counter, pricing-table p/ SaaS */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "arctic-silver",
  meta: {
    title: "Arctic Silver",
    description:
      "Template minimalista prata para SaaS, startups de tecnologia e produtos digitais B2B.",
  },
  theme: {
    colors: {
      gold: "#A1A1AA",
      goldLight: "#D4D4D8",
      goldDark: "#71717A",
      background: "#09090B",
      foreground: "#FAFAFA",
      beige: "#18181B",
      nude: "#27272A",
      cream: "#0F0F12",
    },
    fonts: {
      heading: "Inter",
      body: "Inter",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Proposta SaaS",
        titleLine1: "Plataforma",
        titleHighlight: "Sob Medida",
        subtitle:
          "Desenvolvimento de software personalizado para automatizar processos, escalar operacoes e gerar vantagem competitiva.",
        clientName: "Nome da Empresa",
        ctaPrimary: { label: "Ver Proposta", scrollTo: "counter-1" },
        ctaSecondary: { label: "Agendar Call", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["SaaS", "API", "Dashboard", "Integracao", "Cloud", "Microservicos", "DevOps", "Seguranca"],
        speed: "slow",
        direction: "right",
        variant: "outline",
        separator: "slash",
        size: "sm",
        repeat: 4,
        pauseOnHover: false,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Credenciais",
        title: "Em Numeros",
        subtitle: "",
        items: [
          { value: 40, prefix: "+", suffix: "", label: "Produtos Lancados" },
          { value: 99, prefix: "", suffix: ".9%", label: "Uptime Garantido" },
          { value: 15, prefix: "", suffix: "M+", label: "Usuarios Ativos" },
          { value: 6, prefix: "", suffix: " anos", label: "No Mercado" },
        ],
        columns: 4,
        duration: 1800,
        style: "bordered",
      },
    },
    {
      id: "diag-1",
      type: "diagnostico",
      visible: true,
      data: {
        sectionLabel: "Assessment",
        title: "Desafios Identificados",
        subtitle: "Mapeamos as dores que um software sob medida pode resolver para sua operacao.",
        showImages: false,
        imagesLabel: "",
        images: [],
        cards: [
          { icon: "Settings", title: "Processos Manuais", description: "Tarefas repetitivas feitas manualmente consomem horas da equipe e estao sujeitas a erros humanos.", severity: "alto" },
          { icon: "Database", title: "Dados Fragmentados", description: "Informacoes espalhadas em planilhas, emails e sistemas diferentes. Zero visibilidade integrada.", severity: "alto" },
          { icon: "Lock", title: "Dependencia de Ferramentas", description: "Ferramentas genericas que nao atendem suas necessidades especificas e custam caro.", severity: "medio" },
          { icon: "Rocket", title: "Oportunidade de Escala", description: "Com processos automatizados, sua operacao pode 10x sem aumentar headcount proporcionalmente.", severity: "positivo" },
        ],
      },
    },
    {
      id: "estrategia-1",
      type: "estrategia",
      visible: true,
      data: {
        sectionLabel: "Arquitetura",
        title: "Solucao Proposta",
        subtitle: "Plataforma modular que cresce com seu negocio.",
        cards: [
          {
            icon: "Layout",
            title: "Dashboard & Interface",
            description: "Interface intuitiva que centraliza todas as operacoes em um so lugar.",
            items: ["Dashboard com KPIs em tempo real", "Interface responsiva (web + mobile)", "Permissoes por perfil de usuario", "Dark/light mode"],
          },
          {
            icon: "Server",
            title: "Backend & API",
            description: "Infraestrutura robusta, segura e escalavel para suportar seu crescimento.",
            items: ["API RESTful documentada", "Autenticacao JWT + SSO", "Webhooks para integracao", "Logs e auditoria completa"],
          },
          {
            icon: "Plug",
            title: "Integracoes",
            description: "Conectamos sua plataforma com todas as ferramentas que voce ja usa.",
            items: ["ERP e CRM (Salesforce, HubSpot)", "Gateways de pagamento", "Servicos de email e notificacao", "APIs de terceiros sob demanda"],
          },
        ],
      },
    },
    {
      id: "pricing-1",
      type: "pricing-table",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Modalidades de Projeto",
        subtitle: "Flexibilidade para atender seu escopo e orcamento.",
        plans: [
          {
            name: "MVP",
            badge: "",
            price: "R$ 35k",
            currency: "",
            period: "",
            features: [
              "Escopo enxuto e funcional",
              "4-6 semanas de desenvolvimento",
              "Design system basico",
              "Deploy em cloud",
              "1 mes de suporte",
            ],
            ctaLabel: "Briefing Gratuito", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
          {
            name: "Produto Completo",
            badge: "Recomendado",
            price: "R$ 75k",
            currency: "",
            period: "",
            features: [
              "Escopo completo e escalavel",
              "8-12 semanas de desenvolvimento",
              "Design system premium",
              "Integracoes avancadas",
              "3 meses de suporte",
              "Treinamento da equipe",
            ],
            ctaLabel: "Iniciar Projeto", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: true,
          },
          {
            name: "Squad Dedicada",
            badge: "",
            price: "R$ 25k",
            currency: "",
            period: "/mes",
            features: [
              "Time exclusivo para seu produto",
              "2 devs + 1 designer + PM",
              "Sprints semanais",
              "Evolucao continua",
              "SLA garantido",
              "Escopo flexivel",
            ],
            ctaLabel: "Montar Squad", ctaUrl: "https://wa.me/5500000000000", description: "",
            highlighted: false,
          },
        ],
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Visao",
        title: "Sua Plataforma, Seu Diferencial",
        subtitle: "Imagine ter um software feito sob medida que e seu maior diferencial competitivo.",
        items: [
          { icon: "Zap", label: "Operacao automatizada que roda sem fricao" },
          { icon: "BarChart3", label: "Visibilidade total com dashboards em tempo real" },
          { icon: "TrendingUp", label: "Escala sem limite de ferramentas de terceiros" },
          { icon: "Shield", label: "Dados seguros sob seu controle total" },
        ],
        quote: "Software sob medida nao e luxo. E a unica forma de ter um sistema que faz exatamente o que voce precisa.",
        quoteHighlight: "exatamente o que voce precisa",
        footerClientName: "Nome da Empresa",
        footerNote: "Proposta valida por 15 dias. Projeto sob NDA.",
      },
    },
  ],
};
