import { ProposalConfig } from "@/types/proposal";

/* ── PRO V2: Crimson Bold ── Premium com marquee, counter, timeline, depoimentos */
export const templateConfig: ProposalConfig = {
  version: 2,
  templateId: "crimson-bold",
  meta: {
    title: "Crimson Bold",
    description:
      "Template ousado dark com vermelho intenso para agencias de marketing, publicidade e branding.",
  },
  theme: {
    colors: {
      gold: "#DC2626",
      goldLight: "#EF4444",
      goldDark: "#B91C1C",
      background: "#0A0404",
      foreground: "#FEE2E2",
      beige: "#1C0A0A",
      nude: "#2D1212",
      cream: "#0F0606",
    },
    fonts: {
      heading: "Archivo Black",
      body: "Work Sans",
    },
  },
  sections: [],
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      visible: true,
      data: {
        badge: "Full Service Agency",
        titleLine1: "Marketing",
        titleHighlight: "Que Gera Impacto",
        subtitle:
          "Agencia full-service para marcas que querem dominar. Estrategia, criativos e performance integrados em uma operacao de guerra.",
        clientName: "Nome da Empresa",
        ctaPrimary: { label: "Ver Servicos", scrollTo: "counter-1" },
        ctaSecondary: { label: "Briefing Gratuito", url: "https://wa.me/5500000000000" },
      },
    },
    {
      id: "marquee-1",
      type: "marquee",
      visible: true,
      data: {
        items: ["Branding", "Performance", "Social Media", "Criativos", "SEO", "CRM", "Automacao", "Influencers"],
        speed: "fast",
        direction: "left",
        variant: "solid",
        separator: "slash",
        size: "lg",
        repeat: 3,
        pauseOnHover: false,
      },
    },
    {
      id: "counter-1",
      type: "counter",
      visible: true,
      data: {
        sectionLabel: "Track Record",
        title: "Numeros de Verdade",
        subtitle: "Resultados acumulados da nossa operacao.",
        items: [
          { value: 120, prefix: "+", suffix: "", label: "Marcas Atendidas" },
          { value: 25, prefix: "R$", suffix: "M+", label: "Em Vendas Geradas" },
          { value: 15, prefix: "", suffix: "", label: "Premios de Criatividade" },
          { value: 92, prefix: "", suffix: "%", label: "Retencao de Clientes" },
        ],
        columns: 4,
        duration: 2000,
        style: "card",
      },
    },
    {
      id: "diag-1",
      type: "diagnostico",
      visible: true,
      data: {
        sectionLabel: "Audit",
        title: "O Que Identificamos",
        subtitle: "Analise rapida dos pontos que estao limitando o potencial da sua marca no mercado.",
        showImages: false,
        imagesLabel: "",
        images: [],
        cards: [
          { icon: "Megaphone", title: "Comunicacao Fragmentada", description: "Mensagens diferentes em cada canal. Sem narrativa unica, a marca perde forca e reconhecimento.", severity: "alto" },
          { icon: "Eye", title: "Criativos Previsíveis", description: "Anuncios e conteudo que nao param o scroll. Sem criativos disruptivos, voce e mais um no feed.", severity: "alto" },
          { icon: "Target", title: "Publico Mal Definido", description: "Campanhas atiramando para todos os lados. Sem segmentacao, o investimento e diluido.", severity: "medio" },
          { icon: "Diamond", title: "Marca com DNA Forte", description: "Sua marca tem historia e valores autentiticos. Com a estrategia certa, o potencial e enorme.", severity: "positivo" },
        ],
      },
    },
    {
      id: "timeline-1",
      type: "timeline",
      visible: true,
      data: {
        sectionLabel: "Onboarding",
        title: "Como Trabalhamos",
        subtitle: "Do briefing ao resultado em semanas, nao meses.",
        items: [
          { icon: "MessageSquare", title: "Briefing & Imersao", description: "Sessao de imersao na marca, produto, publico e concorrencia. Tudo documentado.", period: "Dia 1-3" },
          { icon: "Lightbulb", title: "Estrategia & Planejamento", description: "Plano de ataque com canais, mensagens, cronograma e metricas de sucesso.", period: "Dia 4-7" },
          { icon: "Paintbrush", title: "Producao Criativa", description: "Primeiro lote de criativos, copys e campanhas prontos para o ar.", period: "Dia 8-14" },
          { icon: "Rocket", title: "Go Live & Otimizacao", description: "Campanhas no ar com monitoramento diario e otimizacao continua.", period: "Dia 15+" },
        ],
        layout: "alternating",
        connectorStyle: "solid",
      },
    },
    {
      id: "depoimentos-1",
      type: "depoimentos",
      visible: true,
      data: {
        sectionLabel: "Clientes",
        title: "O Que Dizem Sobre Nos",
        items: [
          { name: "Rafael Mendes", role: "CEO, TechStart", avatar: "", text: "Dobramos o faturamento em 4 meses. A agencia entende de resultado, nao so de branding bonito." },
          { name: "Camila Torres", role: "CMO, FoodBrand", avatar: "", text: "Pela primeira vez temos uma agencia que pensa como parceira de negocio, nao como fornecedora." },
          { name: "Pedro Alves", role: "Founder, EduPlat", avatar: "", text: "Os criativos deles sao insanos. Taxa de clique 3x maior que qualquer agencia anterior." },
        ],
      },
    },
    {
      id: "investimento-1",
      type: "investimento",
      visible: true,
      data: {
        sectionLabel: "Investimento",
        title: "Fee Mensal",
        subtitle: "Investimento em marketing com retorno mensuravel.",
        badge: "Full Service",
        priceOriginal: "R$ 12.000",
        priceCurrent: "R$ 8.900",
        priceCurrency: "R$",
        pricePeriod: "/mes",
        description: "Operacao completa de marketing: estrategia, criativos, performance e relatorios.",
        includedItems: [
          "Estrategia de marketing integrada",
          "Gestao de trafego (Meta + Google + TikTok)",
          "40+ criativos novos por mes",
          "Gestao de redes sociais",
          "Relatorio semanal + dashboard",
          "Reuniao semanal de alinhamento",
          "Equipe dedicada (estrategista + designer + gestor)",
        ],
        ctaLabel: "Comecar Parceria",
        ctaUrl: "https://wa.me/5500000000000",
        guarantee: "Contrato trimestral. Se nao houver melhoria em 90 dias, encerramos sem multa.",
      },
    },
    {
      id: "visao-1",
      type: "visao",
      visible: true,
      data: {
        sectionLabel: "Impacto",
        title: "Sua Marca no Topo",
        subtitle: "Imagine sua marca sendo referencia no mercado, com marketing que realmente funciona.",
        items: [
          { icon: "TrendingUp", label: "Crescimento acelerado com marketing integrado" },
          { icon: "Megaphone", label: "Marca reconhecida e respeitada no mercado" },
          { icon: "DollarSign", label: "ROI claro em cada real investido" },
          { icon: "Users", label: "Base de clientes crescendo organicamente" },
        ],
        quote: "Marketing nao e sobre gastar mais. E sobre pensar melhor, criar melhor e executar com obsessao por resultado.",
        quoteHighlight: "obsessao por resultado",
        footerClientName: "Nome da Empresa",
        footerNote: "Proposta valida por 7 dias.",
      },
    },
  ],
};
